Comment Building Blocks.yaml file

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -1,23 +1,23 @@
-name: 01-Building Blocks
+# name: 01-Building Blocks
 
-on:
-  - push
-  - workflow_dispatch
+# on:
+#   - push
+#   - workflow_dispatch
 
-jobs:
-    echo-hello:
-      runs-on: ubuntu-latest
-      steps:
-        - name: Say Hello
-          run: echo "Hello, World!"
+# jobs:
+#     echo-hello:
+#       runs-on: ubuntu-latest
+#       steps:
+#         - name: Say Hello
+#           run: echo "Hello, World!"
 
-    echo-goodbye:
-      runs-on: ubuntu-latest
-      steps:
-        - name: Failed Step
-          run: |
-            echo "I will fail"
-            exit 1
-        - name: Say Goodbye
-          run: echo "Goodbye!!"
+#     echo-goodbye:
+#       runs-on: ubuntu-latest
+#       steps:
+#         - name: Failed Step
+#           run: |
+#             echo "I will fail"
+#             exit 1
+#         - name: Say Goodbye
+#           run: echo "Goodbye!!"
 
